### ISSUE TITLE
_NORMALIZED_BRANCH_NAME set to blank, always failing on "delete prev branch" step

### ISSUE THREAD

**Issue by mewc** [tinybirdco/ci#94]
```
Run output=$(tb --host *** --token *** branch ls)
  output=$(tb --host *** --token *** branch ls)
  BRANCH_NAME="tmp_ci_${_NORMALIZED_BRANCH_NAME}_3"
  
  # Check if the branch name exists in the output
  if echo "$output" | grep -q "\b$BRANCH_NAME\b"; then
      tb \
        --host *** \
        --token *** \
        branch rm $BRANCH_NAME \
        --yes
  else
      echo "Skipping clean up: The Branch '$BRANCH_NAME' does not exist."
  fi
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.11/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.11/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.11/x64
    Python[2](https://github.com/xxxxxx/data/actions/runs/13106758729/job/36562792985?pr=3#step:10:2)_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.11/x64
    Python[3](https://github.com/xxxxxx/data/actions/runs/13106758729/job/36562792985?pr=3#step:10:3)_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.11/x6[4](https://github.com/xxxxxx/data/actions/runs/13106758729/job/36562792985?pr=3#step:10:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.11/x[6](https://github.com/xxxxxx/data/actions/runs/13106758729/job/36562792985?pr=3#step:10:6)4/lib
    GIT_BRANCH: tinybirdsetup
    _ENV_FLAGS: --last-partition --wait
    _NORMALIZED_BRANCH_NAME: 
    TB_ENV: 
    VERSION: 0.0.0
```

it seems like the _NORMALIZED_BRANCH_NAME is set to blank in the CI runs. Always failing on the "delete prev branch" step

my workflow

```
    jobs:
        ci: 
          uses: tinybirdco/ci/.github/workflows/ci.yml@main
          with:
            data_project_dir: tinybird
            tb_format: true
            git_depth: 2
          secrets:
            tb_admin_token: ${{ secrets.TINYBIRD_ADMIN_TOKEN }}  # set admin token associated to an account in GitHub secrets
            tb_host: https://api.us-east.tinybird.co
```
